### ISSUE TITLE
Sdk 1.2.9 is Crashing in iOS Simulator iPhone 5s iOS 12.1 but works in Actual device

### ISSUE THREAD

**Issue by chanonly123** [voxeet/voxeet-ios-sdk#9]
**Describe the bug**

Sample app from github 1.2.8, 1.2.9 is crashing in iOS simulator iPhone 5, 5s iOS 12.1 (may be on others also). By simply joining to any conf id, but working in actual device iPhone 5s iOS 12.1. XCode 10.1.
This may be Heap Corruption issue. So enabling Malloc Guard would help.

**Expected Behaviour**

Excepted behaviour is to complete joining process and start exchanging voice or video

**Steps to Reproduce the Problem**

  1. Download or Clone this sample app
  2. Setup project with Carthage and valid product keys
  3. Enable Malloc Guard (to detect memory issue)
  3. Run on MacOS simulator 5s (tested issue)
  4. Run also in Actual device
  5. Click `Join Conference` on both device
  6. Set conf id "abcd" (any) for both device and click `Join`
  5. App in simulator should crash just before both joins.

**Minimalistic code (recommended)**

Given sample code is sufficient to reproduce.

**Specifications**

  - Device: iPhone5s simulator
  - OS: iOS 12.1
  - Platform: iOS
  - Subsystem: [e.g. n.a., CyanogenMod, ...]
  - Version:
     Not other than anything but Sample app
  - Hardware:

**Comment by VTCoco** [comment]
Hello @chanonly123, I can successfully reproduce your crash.VoxeetSDK isn't compatible with Guard Malloc

**Comment by VTCoco** [comment]
Hello @chanonly123, I can successfully reproduce your crash. VoxeetSDK isn't compatible with Guard Malloc...

**Comment by chanonly123** [comment]
Guard malloc is a utility / tool to detect bad memory access immediately as it occurs, and gives early sign of Heap Corruption that may happen down the line in app's session. Without this utility, the app can have a corrupt heap and continue to work "normally" and crash randomly at a later point, giving you no clue what caused the Heap to get corrupted.

We have been struggling with Heap Corruption issues ever since the Voxeet SDK was integrated with our iOS app, and finally we seem to have found the root cause.

I dont think it is about being compatible. It is simply a diagnostic tool which tells where bad memory access is happening. And in this case as soon as you make 2 users join a Voxeet Conference, Guard Malloc forces the app to crash, which means there is some bad memory access involved.

For more details, read this: https://developer.apple.com/library/archive/documentation/Performance/Conceptual/ManagingMemory/Articles/MallocDebug.html

**Comment by codlab** [comment]
The issue you are facing is not concerning a leak in memory allocation. Corrupted heap is not involved in the conference creation where it has not even initialized the main native part.

But the crash you are facing now is completely related to the way this tool is working internally in the simulator (please refer to the various issues found via Google). MG is replacing the standard malloc library and due to native linking flags and binary structure, the object layout leads to critical fault leading to unallocated memory access.

It is simply a diagnostic tool but has its own side unmanaged side effects. Not that in our replication tests the app really crashes "before" the 2 users join the conference (!)

Did you try the various elements the documentation gives you if you really want to use this tool?

It is scheduled to have a plan to investigate further on this specific point.

**Comment by chanonly123** [comment]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/13619184/54128404-04238100-4432-11e9-8dfc-ef246067e2c8.gif)
<img width="1432" alt="Screenshot 2019-03-11 at 7 11 45 PM" src="https://user-images.githubusercontent.com/13619184/54128420-0c7bbc00-4432-11e9-879b-f8ece98b3215.png">

Sample app also crashes Guard Malloc turned off, by joining and hanging up continuously 3-4 times.

**Comment by codlab** [comment]
This crash is not related to your memory allocation issue. It is mostly due to the different memory layout of the VM and the physical devices.

A Corrupted heap may not lead to the app having memory leak but crashes. Since those are not reproduced on physical devices, we'll flag them to enhancement and future investigation for the simulator but can't allocate much more right now on it.

**Comment by chanonly123** [comment]
Also able to make the voxeet sample app crash on real device. Had kept MG off on real device, so that can't be pointed out as the reason ;) Just try 15-20 times join-leave-join and you will be faced with "EXC_BAD_ACCESS" which causes Heap to get corrupted and ultimately will cause the app to crash at random place.

Device: iPhone 5s, iOS 12.1, Voxeet v1.2.9



<img width="1440" alt="Screenshot 2019-03-11 at 7 35 38 PM" src="https://user-images.githubusercontent.com/13619184/54129843-2c60af00-4435-11e9-9fec-dcea61d19d24.png">

**Comment by codlab** [comment]
So it has nothing to do with the leak that you were referring previously. Please take care not to mix issues ^^

The issue is interesting in this case, we have seen a possible async/barrier call. This is the typical example where MG can not help. Please keep posting this kind of issues, the logs that the screenshot show are extremely useful here. Thanks for the share

**Comment by VTCoco** [comment]
To be more precise with your first issue with **Guard Malloc**, WebRTC uses a custom malloc and isn't compatible with this Xcode tool.
That's why it crashes when a conference is started.

**Comment by chanonly123** [comment]
Just to let you know that we also use Tokbox lib which also uses WebRTC lib. We tested on simulator with Guard Malloc turned on, and it runs smoothly without any crash.

**Comment by VTCoco** [comment]
(it's because of our compilation)

**Comment by VTCoco** [comment]
(but we taking a look to double check)
For now we are still on yesterday problems.

**Comment by codlab** [comment]
To confirm but tokbox may be using outdated of different flavored version of the various libraries in the compilation tree. Google and GM compatibility have a lot of interesting results about its internal stability.

The whole new trace tool provided in XCode is very powerful and does not have the random side effects the GM tools have.

We have provided you trace from our various tests, it would be really great to have feedback from your side with your own traces

**Comment by VTCoco** [comment]
@chanonly123 **Guard Malloc** is compatible with the next release (v1.3.0 today) :)
It wasn't compatible with our previous WebRTC version.

**Comment by VTCoco** [comment]
Simulator is more stable with the latest release (1.3.2).
All issues from this post should be patched, thank you for your reports :)
